package bitwalking.bitwalking.registration_and_login;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import bitwalking.bitwalking.util.Logger;

/**
 * Created by Marcus on 12/8/15.
 */
public class IsoToPhone {

    public static String getPhone(String code) {
        return country2phone.get(code.toUpperCase());
    }

    public static String getCountryName(String code) {
        return country2name.get(code.toUpperCase());
    }

    public static Map<String, String> getAllCodes() {
        return country2phone;
    }

    public static Map<String, String> getAllNames() {
        return country2name;
    }

    private static Map<String, String> country2name = new HashMap<String, String>();
    static {
        country2name.put("KH", "Cambodia");
        country2name.put("MV", "Maldives");
        country2name.put("PF", "French Polynesia");
        country2name.put("GT", "Guatemala");
        country2name.put("SE", "Sweden");
        country2name.put("GB", "United Kingdom");
        country2name.put("SR", "Suriname");
        country2name.put("NL", "Netherlands");
        country2name.put("GL", "Greenland");
        country2name.put("AD", "Andorra");
        country2name.put("DJ", "Djibouti");
        country2name.put("NE", "Niger");
        country2name.put("IO", "British Indian Ocean Territory");
        country2name.put("LU", "Luxembourg");
        country2name.put("ZA", "South Africa");
        country2name.put("VA", "Vatican City");
        country2name.put("IE", "Ireland");
        country2name.put("FM", "Micronesia");
        country2name.put("KM", "Comoros");
        country2name.put("GN", "Guinea");
        country2name.put("CS", "Serbia");
        country2name.put("HT", "Haiti");
        country2name.put("CR", "Costa Rica");
        country2name.put("MU", "Mauritius");
        country2name.put("MO", "Macau");
        country2name.put("MM", "Myanmar (Burma)");
        country2name.put("TA", "Tristan da Cunha");
        country2name.put("BY", "Belarus");
        country2name.put("SY", "Syria");
        country2name.put("GP", "Guadeloupe");
        country2name.put("VI", "U.S. Virgin Islands");
        country2name.put("IR", "Iran");
        country2name.put("AS", "American Samoa");
        country2name.put("EG", "Egypt");
        country2name.put("AL", "Albania");
        country2name.put("PE", "Peru");
        country2name.put("AW", "Aruba");
        country2name.put("ES", "Spain");
        country2name.put("TH", "Thailand");
        country2name.put("ZM", "Zambia");
        country2name.put("GU", "Guam");
        country2name.put("BS", "Bahamas");
        country2name.put("AG", "Antigua & Barbuda");
        country2name.put("AR", "Argentina");
        country2name.put("MC", "Monaco");
        country2name.put("SG", "Singapore");
        country2name.put("LC", "St. Lucia");
        country2name.put("FI", "Finland");
        country2name.put("FJ", "Fiji");
        country2name.put("BG", "Bulgaria");
        country2name.put("KN", "St. Kitts & Nevis");
        country2name.put("MW", "Malawi");
        country2name.put("BA", "Bosnia & Herzegovina");
        country2name.put("TD", "Chad");
        country2name.put("MS", "Montserrat");
        country2name.put("CA", "Canada");
        country2name.put("MD", "Moldova");
        country2name.put("US", "United States");
        country2name.put("SB", "Solomon Islands");
        country2name.put("CI", "Côte d’Ivoire");
        country2name.put("RW", "Rwanda");
        country2name.put("NU", "Niue");
        country2name.put("AE", "United Arab Emirates");
        country2name.put("CO", "Colombia");
        country2name.put("YE", "Yemen");
        country2name.put("AT", "Austria");
        country2name.put("CY", "Cyprus");
        country2name.put("EH", "Western Sahara");
        country2name.put("NP", "Nepal");
        country2name.put("KW", "Kuwait");
        country2name.put("CN", "China");
        country2name.put("NF", "Norfolk Island");
        country2name.put("JE", "Jersey");
        country2name.put("CX", "Christmas Island");
        country2name.put("GD", "Grenada");
        country2name.put("HN", "Honduras");
        country2name.put("SH", "St. Helena");
        country2name.put("CV", "Cape Verde");
        country2name.put("CF", "Central African Republic");
        country2name.put("LS", "Lesotho");
        country2name.put("BN", "Brunei");
        country2name.put("ML", "Mali");
        country2name.put("BW", "Botswana");
        country2name.put("AN", "Netherlands Antilles");
        country2name.put("MK", "Macedonia (FYROM)");
        country2name.put("BE", "Belgium");
        country2name.put("CL", "Chile");
        country2name.put("CG", "Congo (Republic)");
        country2name.put("SZ", "Swaziland");
        country2name.put("SI", "Slovenia");
        country2name.put("FK", "Falkland Islands (Islas Malvinas)");
        country2name.put("GG", "Guernsey");
        country2name.put("IT", "Italy");
        country2name.put("VU", "Vanuatu");
        country2name.put("MP", "Northern Mariana Islands");
        country2name.put("ZW", "Zimbabwe");
        country2name.put("TM", "Turkmenistan");
        country2name.put("CK", "Cook Islands");
        country2name.put("IL", "Israel");
        country2name.put("DK", "Denmark");
        country2name.put("TW", "Taiwan");
        country2name.put("TO", "Tonga");
        country2name.put("YT", "Mayotte");
        country2name.put("RS", "Serbia");
        country2name.put("TJ", "Tajikistan");
        country2name.put("TL", "Timor-Leste");
        country2name.put("PK", "Pakistan");
        country2name.put("AU", "Australia");
        country2name.put("TN", "Tunisia");
        country2name.put("HU", "Hungary");
        country2name.put("SC", "Seychelles");
        country2name.put("TT", "Trinidad & Tobago");
        country2name.put("GE", "Georgia");
        country2name.put("BH", "Bahrain");
        country2name.put("TZ", "Tanzania");
        country2name.put("AM", "Armenia");
        country2name.put("LR", "Liberia");
        country2name.put("KE", "Kenya");
        country2name.put("RE", "Réunion");
        country2name.put("AF", "Afghanistan");
        country2name.put("AI", "Anguilla");
        country2name.put("PT", "Portugal");
        country2name.put("QA", "Qatar");
        country2name.put("ER", "Eritrea");
        country2name.put("PW", "Palau");
        country2name.put("FO", "Faroe Islands");
        country2name.put("CC", "Cocos (Keeling) Islands");
        country2name.put("GH", "Ghana");
        country2name.put("LV", "Latvia");
        country2name.put("AO", "Angola");
        country2name.put("KP", "North Korea");
        country2name.put("NR", "Nauru");
        country2name.put("VG", "British Virgin Islands");
        country2name.put("SJ", "Svalbard & Jan Mayen");
        country2name.put("PS", "Palestine");
        country2name.put("IS", "Iceland");
        country2name.put("PA", "Panama");
        country2name.put("ST", "São Tomé & Príncipe");
        country2name.put("NO", "Norway");
        country2name.put("GF", "French Guiana");
        country2name.put("MT", "Malta");
        country2name.put("RU", "Russia");
        country2name.put("TC", "Turks & Caicos Islands");
        country2name.put("JP", "Japan");
        country2name.put("GI", "Gibraltar");
        country2name.put("IQ", "Iraq");
        country2name.put("SV", "El Salvador");
        country2name.put("GM", "Gambia");
        country2name.put("KI", "Kiribati");
        country2name.put("BR", "Brazil");
        country2name.put("MZ", "Mozambique");
        country2name.put("LI", "Liechtenstein");
        country2name.put("ID", "Indonesia");
        country2name.put("HR", "Croatia");
        country2name.put("VE", "Venezuela");
        country2name.put("GR", "Greece");
        country2name.put("BI", "Burundi");
        country2name.put("SA", "Saudi Arabia");
        country2name.put("CH", "Switzerland");
        country2name.put("SN", "Senegal");
        country2name.put("SO", "Somalia");
        country2name.put("WS", "Samoa");
        country2name.put("BB", "Barbados");
        country2name.put("UZ", "Uzbekistan");
        country2name.put("ET", "Ethiopia");
        country2name.put("TV", "Tuvalu");
        country2name.put("BZ", "Belize");
        country2name.put("NG", "Nigeria");
        country2name.put("SD", "Sudan");
        country2name.put("MR", "Mauritania");
        country2name.put("MH", "Marshall Islands");
        country2name.put("ME", "Montenegro");
        country2name.put("PH", "Philippines");
        country2name.put("TK", "Tokelau");
        country2name.put("SL", "Sierra Leone");
        country2name.put("LY", "Libya");
        country2name.put("VC", "St. Vincent & Grenadines");
        country2name.put("AC", "Ascension Island");
        country2name.put("MX", "Mexico");
        country2name.put("BD", "Bangladesh");
        country2name.put("WF", "Wallis & Futuna");
        country2name.put("BM", "Bermuda");
        country2name.put("CZ", "Czech Republic");
        country2name.put("IM", "Isle of Man");
        country2name.put("MN", "Mongolia");
        country2name.put("CD", "Congo (DRC)");
        country2name.put("MA", "Morocco");
        country2name.put("IN", "India");
        country2name.put("JO", "Jordan");
        country2name.put("NI", "Nicaragua");
        country2name.put("NZ", "New Zealand");
        country2name.put("PL", "Poland");
        country2name.put("PG", "Papua New Guinea");
        country2name.put("AZ", "Azerbaijan");
        country2name.put("TG", "Togo");
        country2name.put("BO", "Bolivia");
        country2name.put("DM", "Dominica");
        country2name.put("BF", "Burkina Faso");
        country2name.put("MY", "Malaysia");
        country2name.put("BJ", "Benin");
        country2name.put("DZ", "Algeria");
        country2name.put("NA", "Namibia");
        country2name.put("LT", "Lithuania");
        country2name.put("SM", "San Marino");
        country2name.put("NC", "New Caledonia");
        country2name.put("EC", "Ecuador");
        country2name.put("JM", "Jamaica");
        country2name.put("GQ", "Equatorial Guinea");
        country2name.put("EE", "Estonia");
        country2name.put("UA", "Ukraine");
        country2name.put("LB", "Lebanon");
        country2name.put("CU", "Cuba");
        country2name.put("KZ", "Kazakhstan");
        country2name.put("VN", "Vietnam");
        country2name.put("PR", "Puerto Rico");
        country2name.put("LA", "Laos");
        country2name.put("BT", "Bhutan");
        country2name.put("KG", "Kyrgyzstan");
        country2name.put("GY", "Guyana");
        country2name.put("KY", "Cayman Islands");
        country2name.put("SK", "Slovakia");
        country2name.put("DO", "Dominican Republic");
        country2name.put("UG", "Uganda");
        country2name.put("FR", "France");
        country2name.put("OM", "Oman");
        country2name.put("DE", "Germany");
        country2name.put("UY", "Uruguay");
        country2name.put("MG", "Madagascar");
        country2name.put("KR", "South Korea");
        country2name.put("RO", "Romania");
        country2name.put("GA", "Gabon");
        country2name.put("PY", "Paraguay");
        country2name.put("HK", "Hong Kong");
        country2name.put("LK", "Sri Lanka");
        country2name.put("TR", "Turkey");
        country2name.put("MQ", "Martinique");
        country2name.put("GW", "Guinea-Bissau");
        country2name.put("CM", "Cameroon");
        country2name.put("PM", "St. Pierre & Miquelon");
        country2name.put("XK", "Kosovo");
    }

    private static Map<String, String> country2phone = new HashMap<String, String>();
    static {
        country2phone.put("AF", "+93");
        country2phone.put("AL", "+355");
        country2phone.put("DZ", "+213");
        country2phone.put("AD", "+376");
        country2phone.put("AO", "+244");
        country2phone.put("AG", "+1268");
        country2phone.put("AR", "+54");
        country2phone.put("AM", "+374");
        country2phone.put("AU", "+61");
        country2phone.put("AT", "+43");
        country2phone.put("AZ", "+994");
        country2phone.put("BS", "+1242");
        country2phone.put("BH", "+973");
        country2phone.put("BD", "+880");
        country2phone.put("BB", "+1246");
        country2phone.put("BY", "+375");
        country2phone.put("BE", "+32");
        country2phone.put("BZ", "+501");
        country2phone.put("BJ", "+229");
        country2phone.put("BT", "+975");
        country2phone.put("BO", "+591");
        country2phone.put("BA", "+387");
        country2phone.put("BW", "+267");
        country2phone.put("BR", "+55");
        country2phone.put("BN", "+673");
        country2phone.put("BG", "+359");
        country2phone.put("BF", "+226");
        country2phone.put("BI", "+257");
        country2phone.put("KH", "+855");
        country2phone.put("CM", "+237");
        country2phone.put("CA", "+1");
        country2phone.put("CV", "+238");
        country2phone.put("CF", "+236");
        country2phone.put("TD", "+235");
        country2phone.put("CL", "+56");
        country2phone.put("CN", "+86");
        country2phone.put("CO", "+57");
        country2phone.put("KM", "+269");
        country2phone.put("CD", "+243");
        country2phone.put("CG", "+242");
        country2phone.put("CR", "+506");
        country2phone.put("CI", "+225");
        country2phone.put("HR", "+385");
        country2phone.put("CU", "+53");
        country2phone.put("CY", "+357");
        country2phone.put("CZ", "+420");
        country2phone.put("DK", "+45");
        country2phone.put("DJ", "+253");
        country2phone.put("DM", "+1767");
        country2phone.put("DO", "+1");
        country2phone.put("EC", "+593");
        country2phone.put("EG", "+20");
        country2phone.put("SV", "+503");
        country2phone.put("GQ", "+240");
        country2phone.put("ER", "+291");
        country2phone.put("EE", "+372");
        country2phone.put("ET", "+251");
        country2phone.put("FJ", "+679");
        country2phone.put("FI", "+358");
        country2phone.put("FR", "+33");
        country2phone.put("GA", "+241");
        country2phone.put("GM", "+220");
        country2phone.put("GE", "+995");
        country2phone.put("DE", "+49");
        country2phone.put("GH", "+233");
        country2phone.put("GR", "+30");
        country2phone.put("GD", "+1473");
        country2phone.put("GT", "+502");
        country2phone.put("GN", "+224");
        country2phone.put("GW", "+245");
        country2phone.put("GY", "+592");
        country2phone.put("HT", "+509");
        country2phone.put("HN", "+504");
        country2phone.put("HU", "+36");
        country2phone.put("IS", "+354");
        country2phone.put("IN", "+91");
        country2phone.put("ID", "+62");
        country2phone.put("IR", "+98");
        country2phone.put("IQ", "+964");
        country2phone.put("IE", "+353");
        country2phone.put("IL", "+972");
        country2phone.put("IT", "+39");
        country2phone.put("JM", "+1876");
        country2phone.put("JP", "+81");
        country2phone.put("JO", "+962");
        country2phone.put("KZ", "+7");
        country2phone.put("KE", "+254");
        country2phone.put("KI", "+686");
        country2phone.put("KP", "+850");
        country2phone.put("KR", "+82");
        country2phone.put("KW", "+965");
        country2phone.put("KG", "+996");
        country2phone.put("LA", "+856");
        country2phone.put("LV", "+371");
        country2phone.put("LB", "+961");
        country2phone.put("LS", "+266");
        country2phone.put("LR", "+231");
        country2phone.put("LY", "+218");
        country2phone.put("LI", "+423");
        country2phone.put("LT", "+370");
        country2phone.put("LU", "+352");
        country2phone.put("MK", "+389");
        country2phone.put("MG", "+261");
        country2phone.put("MW", "+265");
        country2phone.put("MY", "+60");
        country2phone.put("MV", "+960");
        country2phone.put("ML", "+223");
        country2phone.put("MT", "+356");
        country2phone.put("MH", "+692");
        country2phone.put("MR", "+222");
        country2phone.put("MU", "+230");
        country2phone.put("MX", "+52");
        country2phone.put("FM", "+691");
        country2phone.put("MD", "+373");
        country2phone.put("MC", "+377");
        country2phone.put("MN", "+976");
        country2phone.put("ME", "+382");
        country2phone.put("MA", "+212");
        country2phone.put("MZ", "+258");
        country2phone.put("MM", "+95");
        country2phone.put("NA", "+264");
        country2phone.put("NR", "+674");
        country2phone.put("NP", "+977");
        country2phone.put("NL", "+31");
        country2phone.put("NZ", "+64");
        country2phone.put("NI", "+505");
        country2phone.put("NE", "+227");
        country2phone.put("NG", "+234");
        country2phone.put("NO", "+47");
        country2phone.put("OM", "+968");
        country2phone.put("PK", "+92");
        country2phone.put("PW", "+680");
        country2phone.put("PA", "+507");
        country2phone.put("PG", "+675");
        country2phone.put("PY", "+595");
        country2phone.put("PE", "+51");
        country2phone.put("PH", "+63");
        country2phone.put("PL", "+48");
        country2phone.put("PT", "+351");
        country2phone.put("QA", "+974");
        country2phone.put("RO", "+40");
        country2phone.put("RU", "+7");
        country2phone.put("RW", "+250");
        country2phone.put("KN", "+1869");
        country2phone.put("LC", "+1758");
        country2phone.put("VC", "+1784");
        country2phone.put("WS", "+685");
        country2phone.put("SM", "+378");
        country2phone.put("ST", "+239");
        country2phone.put("SA", "+966");
        country2phone.put("SN", "+221");
        country2phone.put("RS", "+381");
        country2phone.put("SC", "+248");
        country2phone.put("SL", "+232");
        country2phone.put("SG", "+65");
        country2phone.put("SK", "+421");
        country2phone.put("SI", "+386");
        country2phone.put("SB", "+677");
        country2phone.put("SO", "+252");
        country2phone.put("ZA", "+27");
        country2phone.put("ES", "+34");
        country2phone.put("LK", "+94");
        country2phone.put("SD", "+249");
        country2phone.put("SR", "+597");
        country2phone.put("SZ", "+268");
        country2phone.put("SE", "+46");
        country2phone.put("CH", "+41");
        country2phone.put("SY", "+963");
        country2phone.put("TJ", "+992");
        country2phone.put("TZ", "+255");
        country2phone.put("TH", "+66");
        country2phone.put("TL", "+670");
        country2phone.put("TG", "+228");
        country2phone.put("TO", "+676");
        country2phone.put("TT", "+1868");
        country2phone.put("TN", "+216");
        country2phone.put("TR", "+90");
        country2phone.put("TM", "+993");
        country2phone.put("TV", "+688");
        country2phone.put("UG", "+256");
        country2phone.put("UA", "+380");
        country2phone.put("AE", "+971");
        country2phone.put("GB", "+44");
        country2phone.put("US", "+1");
        country2phone.put("UY", "+598");
        country2phone.put("UZ", "+998");
        country2phone.put("VU", "+678");
        country2phone.put("VA", "+379");
        country2phone.put("VE", "+58");
        country2phone.put("VN", "+84");
        country2phone.put("YE", "+967");
        country2phone.put("ZM", "+260");
        country2phone.put("ZW", "+263");
        country2phone.put("TW", "+886");
        country2phone.put("CX", "+61");
        country2phone.put("CC", "+61");
        country2phone.put("NF", "+672");
        country2phone.put("NC", "+687");
        country2phone.put("PF", "+689");
        country2phone.put("YT", "+262");
        country2phone.put("PM", "+508");
        country2phone.put("WF", "+681");
        country2phone.put("CK", "+682");
        country2phone.put("NU", "+683");
        country2phone.put("TK", "+690");
        country2phone.put("GG", "+44");
        country2phone.put("IM", "+44");
        country2phone.put("JE", "+44");
        country2phone.put("AI", "+1264");
        country2phone.put("BM", "+1441");
        country2phone.put("IO", "+246");
        country2phone.put("VG", "+1284");
        country2phone.put("KY", "+1345");
        country2phone.put("FK", "+500");
        country2phone.put("GI", "+350");
        country2phone.put("MS", "+1664");
        country2phone.put("SH", "+290");
        country2phone.put("TC", "+1649");
        country2phone.put("MP", "+1670");
        country2phone.put("PR", "+1");
        country2phone.put("AS", "+1684");
        country2phone.put("GU", "+1671");
        country2phone.put("VI", "+1340");
        country2phone.put("HK", "+852");
        country2phone.put("MO", "+853");
        country2phone.put("FO", "+298");
        country2phone.put("GL", "+299");
        country2phone.put("GF", "+594");
        country2phone.put("GP", "+590");
        country2phone.put("MQ", "+596");
        country2phone.put("RE", "+262");
        country2phone.put("AW", "+297");
        country2phone.put("AN", "+599");
        country2phone.put("SJ", "+47");
        country2phone.put("AC", "+247");
        country2phone.put("TA", "+290");
        country2phone.put("CS", "+381");
        country2phone.put("PS", "+970");
        country2phone.put("EH", "+212");
        country2phone.put("XK", "+383");
    }

    public static String getCountryByCode(String code) {
        for (Map.Entry<String, String> c : country2phone.entrySet()) {
            if (c.getValue().equalsIgnoreCase(code))
                return c.getKey();
        }

        return null;
    }

    public static ArrayList<String> getCountriesByCode(String code) {
        ArrayList<String> countries = new ArrayList<>();
        for (Map.Entry<String, String> c : country2phone.entrySet()) {
            if (c.getValue().equalsIgnoreCase(code))
                countries.add(c.getKey());
        }

        return countries;
    }
}
